
const datospelis = [
    {imagen: '/img/11.jpg', titulo: "SPIDERMAN-no way home", texto1:"Genero:Accion:", texto2:"El multiverso desatado. Peter Parker es desenmascarado y por tanto no es capaz de separar su vida normal de los enormes riesgos que conlleva ser un súper héroe. Cuando pide ayuda a Doctor Strange, los riesgos pasan a ser aún más peligrosos.", precio1: "Precio:S/", precio:  10.00 },
    {imagen: '/img/thor love and thunder.jpg', titulo: "THOR LOVE AND THUNDER", texto1:"genero:Accion",  texto2:"La película encuentra a Thor (Chris Hemsworth) en un viaje diferente a todo lo que ha enfrentado: Una búsqueda de la paz interior. Pero su retiro es interrumpido por un asesino galáctico conocido como Gorr el carnicero de dioses (Christian Bale), que busca la extinción de los dioses.", precio1: "Precio:S/", precio: 5.0},
    {imagen: '/img/images.jpg', titulo: "DUNE", texto1:"Genero:Accion", texto2:"Se trata de un joven brillante y de gran talento con un destino grandioso que no comprende todavía y que deberá viajar al planeta más peligroso del universo para asegurar el futuro de su familia y de su pueblo.", precio1: "Precio:S/", precio:  5.00},
    {imagen: '/img/22.jpg', titulo: "starwars:rougue one", texto1:"Genero:Accion", texto2:"Un prominente científico de nombre Galen Walton Erso vive junto a su mujer Lyra y su hija Jyn en el remoto planeta Lah'mu huyendo del Imperio Galáctico que lo busca, hasta que finalmente una pequeña guarnición al mando del director Imperial Orson Callan Krennic da con él y lo insta a que regrese al Imperio", precio1: "Precio:S/", precio:  7.00}, 
    {imagen: '/img/23.jpg', titulo: "BLACK WIDOW", texto1:"Genero:Accion", texto2:"El thriller de espías de Marvel Studios presenta la historia de Natasha Romanoff, también conocida como Black Widow. Ella se enfrenta a lo más oscuro de sus cuentas pendientes cuando surge una peligrosa conspiración que tiene lazos con su pasado.", precio1: "Precio:S/", precio:  11.50}, 
    {imagen: '/img/24.jpg', titulo: "BLACK ADAM", texto1:"Genero:Accion", texto2:"comienza hace 5 000 años, con la ciudad de Kahndaq gobernada por un tirano dedicado a construir una corona mágica que le otorgará grandes poderes. Un niño desencadena la rebelión y, justo cuando el tirano está a punto de ponerse la corona especial, ¡el niño recibe los poderes de Shazam!", precio1: "Precio:S/", precio:  5.50},
    {imagen: '/img/20.jpg', titulo: "BATMAN", texto1:"Genero:Accion", texto2:"Batman es la identidad secreta de Bruce Wayne, un empresario multimillonario, galán y filántropo. Presenció el asesinato de sus padres cuando era niño lo marcó profundamente y lo llevó a entrenarse en la perfección física e intelectual para ponerse un disfraz de murciélago con el fin de combatir el crimen.", precio1: "Precio:S/", precio:  9.50},
    {imagen: '/img/19.jpg', titulo: "WANDA MISION", texto1: "Genero:Accion", texto2:"Wanda Maximoff y Visión son dos seres con superpoderes que intentan adaptarse a una vida suburbana «ideal». Sin embargo, en medio de las divertidas ocurrencias de sus perfectas vidas televisivas, surge la sospecha de que las cosas podrían no ser lo que parecen.",precio1: "Precio:S/", precio:  1.50},
    {imagen: '/img/mad max.jpg', titulo: "MAD MAX", texto1: "Genero:Accion", texto2:"Max Rockatansky, un superviviente del holocausto nuclear atormentado por los recuerdos de todas las personas a las que no pudo proteger, es capturado y llevado a La Ciudadela del señor de la guerra Immortan Joe. Allí, Max es encarcelado y utilizado como 'bolsa de sangre' para Nux, un Media Vida enfermo.", precio1: "Precio:S/", precio:  4.50},
    {imagen: '/img/harrypotter(2).jpg', titulo: "HARRY POTTER", texto1: "Genero:Fant7asia", texto2:"Harry Potter se ha quedado huérfano y vive en casa de sus abominables tíos y el insoportable primo Dudley. Harry se siente muy triste y solo, hasta que un buen día recibe una carta que cambiará su vida para siempre. En ella le comunican que ha sido aceptado como alumno en el Colegio Hogwarts de Magia.", precio1: "Precio:S/", precio:  3.50},
    {imagen: '/img/21.jpg', titulo: "BOHEMIAN RAPSODY", texto1: "Genero:Accion", texto2:"En Bohemian Rhapsody, Freddie Bulsara (Rami Malek) sueña con ser cantante y va a los clubes a escuchar tocar a su grupo favorito. Cuando su cantante principal renuncia, Freddie consigue el trabajo. Cambia su apellido por Mercury y el grupo se convierte en Queen.", precio1: "Precio:S/", precio:  6.50},
    {imagen: '/img/18.jpg', titulo: "MORBIUS", texto1: "Genero:Accion,Sobrenatural", texto2:"El Doctor Michael Morbius (Jared Leto) es un bioquímico que sufre una extraña enfermedad en la sangre. Para curarse y dar una respuesta a su trastorno, en el proceso, se infecta sin darse cuenta con una forma de vampirismo. Aunque debería haber muerto, tras la cura, Michael se siente más vivo que nunca y adquiere dones ,además de una necesidad de consumir sangre.", precio1: "Precio:S/", precio:  3.99},
    {imagen: '/img/17.jpg', titulo: "LIFE", texto1: "Genero:Accion,ciencia", texto2:"Life (Vida) nos sitúa en la Estación Espacial Internacional en donde un grupo de astronautas recuperan unas muestras biológicas de Marte; unas de ellas, tras varios experimentos, toma 'vida' y los astronautas deberán enfrentarse a una forma de vida desconocida para ellos y que luchará para sobrevivir.", precio1: "Precio:S/", precio:  2.30},
    {imagen: '/img/15.jpg', titulo: "Duro de Matar", texto1: "Genero:Accion", texto2:"luego de encontrar evidencia sobre un probable ataque a una serie de hackers, el FBI solicita la ayuda de John McClane, detective de la ciudad de Nueva York, para escoltar a Matt Farrell y llevarlo a Washington para ayudar a esclarecer un probable ataque cibernético. Pero tan pronto lo ha encontrado, son atacados por un grupo de asesinos profesionales.", precio1: "Precio:S/", precio:  8.90},
    {imagen: '/img/DBZMovie13.jpg', titulo: "DRANGON BALL", texto1:"Genero:animado", texto2:"En un día como cualquier otro en Ciudad Satán, Gohan y Videl rescatan a un peculiar anciano que se hace llamar Hoi. Este los recompensa con una caja de música en la que asegura se halla encerrado un mítico héroe del planeta Konats. Ambos reúnen las Esferas del Dragón para abrir dicha caja. De su interior sale Tapion, quien se va diciendo que ha cometido un gran error ", precio1: "Precio:S/", precio:  5.50},
    {imagen: '/img/images (1).jpg', titulo: "EL REY LEON", texto1:"Genero:animado", texto2:"Narra las aventuras de Simba, un cachorro de león que tiene que huir de su reino tras el asesinato de su padre, el rey Mufasa, a manos de su ambicioso tío Scar y su ejército de hienas. Crecerá en la selva, en compañía de un chiflado jabalí y de un suricato inteligente y hedonista.", precio1: "Precio:S/", precio:  4.50},
    {imagen: '/img/blanca-nieves.jpg', titulo: "BLANCA NIEVES", texto1:"Genero:animado", texto2:"Blancanieves es una atractiva joven criada por una malvada Reina quien, envidiando su belleza, decide matarla tendiéndole una trampa en el bosque. Pero la joven consigue escapar y encuentra refugio en una casa habitada por siete simpáticos enanitos.", precio1: "Precio:S/", precio:  1.50},
    {imagen: '/img/unnamed.jpg', titulo: "¿QUE PASO AYER?", texto1: "Genero:Comedia", texto2:"Cuatro amigos se van de “despedida de soltero” a Las Vegas justo un par de días antes del casamiento de uno de ellos. Tras una noche de diversión desenfrenada despiertan con una terrible resaca, hay un bebé en la habitación del hotel, y no tienen la menor idea de lo que sucedió en las horas previas.", precio1: "Precio:S/", precio: 6.50},
    {imagen: '/img/10.jpg', titulo: "VENOM", texto1: "Genero:Accion", texto2:" Eddie lleva tiempo intentando desenmascarar al creador de la Fundación Vida, el famoso genio científico Carlton Drake, una obsesión que ha arruinado su carrera y su relación con su novia, Anne. Al investigar uno de los experimentos de Drake, el ente alienígena Venom se fusiona con el cuerpo de Eddie, y el reportero adquiere de pronto nuevos e increíbles superpoderes", precio1: "Precio:S/", precio:  9.99},
    {imagen: '/img/12.jpg', titulo: "AVENGERS:INFINITY WAR", texto1: "Genero:Accion", texto2:"Habiendo atacado Xandar, lugar donde la Gema del Poder era custodiada por los Nova Corps, y decidido a reclamar el resto de las Gemas del Infinito, Thanos ataca la Statesman de los Asgardianos junto a la Orden Negra. La mitad de los Asgardianos son asesinados mientras Thor, Loki y Heimdall simplemente caen vencidos.", precio1: "Precio:S/", precio:  3.55},
    {imagen: '/img/13.jpg', titulo: "AVENGERS:END GAME", texto1: "Genero:Accion", texto2:"Está ambientada después de los catastróficos sucesos de  Infinity War, en los que Thanos eliminó  a la mitad del universo al usar las gemas del infinito. Los que no se fueron, están desesperados por hacer algo para traer de vuelta a sus seres queridos. Pero después de un primer intento con ayuda extra de la Capitana Marvel que crea más problemas que soluciones", precio1: "Precio:S/", precio:  6.50}

];

export default datospelis;